apiVersion: v1
kind: Service
metadata:
  name: numberone-postgres-service
  namespace: numberone
spec:
  type: ClusterIP
  selector:
    app: numberone-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
