spring:
  application:
    name: numberone
  profiles:
    default: dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  security:
    jwt:
      issuer: numberone-api
      access-token-expiration: 1h
