-- Add missing columns to client table
ALTER TABLE client ADD COLUMN nome VARCHAR(90) NOT NULL;
ALTER TABLE client ADD COLUMN documento VARCHAR(50) NOT NULL;
ALTER TABLE client ADD COLUMN telefone VARCHAR(15) NOT NULL;
ALTER TABLE client ADD COLUMN endereco VARCHAR(90) NOT NULL;
ALTER TABLE client ADD COLUMN ativo BOOLEAN DEFAULT TRUE;
