ALTER TABLE item RENAME TO item_estoque;

ALTER TABLE item_estoque
ADD COLUMN codigo VARCHAR(100),
ADD COLUMN custo_unitario DECIMAL(10,2),
ADD COLUMN preco_venda DECIMAL(10,2),
ADD COLUMN estoque_minimo INTEGER NOT NULL DEFAULT 0,
ADD COLUMN marca VARCHAR(100),
ADD COLUMN veiculo_aplicavel VARCHAR(255) NOT NULL DEFAULT 'UNIVERSAL',
ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN created_at TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP;

ALTER TABLE item_estoque
DROP COLUMN valor_base;
