apiVersion: v1
kind: Service
metadata:
  name: mailpit
  namespace: numberone
spec:
  type: ClusterIP
  selector:
    app: mailpit
  ports:
    - name: smtp
      port: 1025
      targetPort: smtp
    - name: http
      port: 8025
      targetPort: http
