apiVersion: apps/v1
kind: Deployment
metadata:
  name: numberone-api
  namespace: numberone
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-postgres
          command:
            - sh
            - -c
            - |
              until nc -z ${DB_HOST} 5432; do
                echo "Waiting for Postgres..."
                sleep 2
              done
      containers:
        - name: numberone-api
          image: ${APP_IMAGE}
