apiVersion: v1
kind: Secret
metadata:
  name: numberone-api-secret
  namespace: numberone
type: Opaque
stringData:
  DB_USERNAME: "${DB_USERNAME}"
  DB_PASSWORD: "${DB_PASSWORD}"
  JWT_SECRET: "${JWT_SECRET}"
  BOOTSTRAP_ADMIN_USERNAME: "${BOOTSTRAP_ADMIN_USERNAME}"
  BOOTSTRAP_ADMIN_PASSWORD: "${BOOTSTRAP_ADMIN_PASSWORD}"
  MAIL_PASSWORD: "${MAIL_PASSWORD}"
